#!/bin/sh

set -e

if test "$1" = "remove"; then
    if test -x /usr/sbin/update-binfmts; then
        update-binfmts --package llvm-3.8-runtime \
            --remove llvm-3.8-runtime.binfmt /usr/bin/lli-3.8 || true
        if test -f /var/lib/binfmts/llvm-3.8.binfmt; then
            # Purge old file
            update-binfmts --package llvm-3.8-runtime \
                --remove llvm-3.8.binfmt /usr/bin/lli-3.8 || true
        fi
    fi
fi

#DEBHELPER#

