usr/lib/llvm-3.8/lib/libLLVM*.a
#usr/lib/llvm-3.8/lib/libllvm*.a
usr/lib/llvm-3.8/lib/LLVM*.so
usr/lib/llvm-3.8/lib/libLLVM.so
usr/lib/llvm-3.8/lib/libLLVM-3.8.so
usr/lib/llvm-3.8/lib/libLLVM-3.8.1.so
usr/lib/llvm-3.8/lib/libLTO.*
usr/lib/llvm-3.8/lib/BugpointPasses.so
usr/lib/llvm-3.8/include/llvm/      usr/include/llvm-3.8/
usr/lib/llvm-3.8/include/llvm-c/	usr/include/llvm-c-3.8/
# Explicit debian/tmp since there are multiple declarations
debian/tmp/usr/lib/llvm-3.8/share/llvm/cmake/*.cmake

utils/vim/indent/llvm-3.8.vim		        usr/share/vim/addons/indent/

utils/vim/syntax/llvm-3.8.vim		        usr/share/vim/addons/syntax/
utils/vim/syntax/tablegen-3.8.vim		    usr/share/vim/addons/syntax/

utils/vim/ftdetect/llvm-3.8.vim		        usr/share/vim/addons/ftdetect/
utils/vim/ftdetect/tablegen-3.8.vim		    usr/share/vim/addons/ftdetect/

utils/vim/ftplugin/llvm-3.8.vim		        usr/share/vim/addons/ftplugin/
utils/vim/ftplugin/tablegen-3.8.vim		    usr/share/vim/addons/ftplugin/

utils/vim/llvm-3.8-vimrc		            usr/share/vim/addons


utils/emacs/emacs.el		    usr/share/emacs/site-lisp/llvm-3.8/
utils/emacs/llvm-mode.el	    usr/share/emacs/site-lisp/llvm-3.8/
utils/emacs/tablegen-mode.el	usr/share/emacs/site-lisp/llvm-3.8/

